services:
  - addr: 'https://vk.com'
    ip: 'vk.com'
    expected_status: 200
nginx_config_path: './example/nginx.conf'
ticker: '1s'
pattern_addr: 'server %s;'
before:
  'http {
       upstream myapp1 {'
after:
  '}

       server {
           listen 80;

           location / {
               proxy_pass http://myapp1;
           }
       }
   }'