version: '3'

services:
#  server:
#    container_name: back
#    restart: always
#    command: ./main -port=:80 -metrics=:8080
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    ports:
#      - '8000:80'
#      - '8080:8080'

  #  MONITORING
  prometheus:
    container_name: 5factorial-monitoring-prometheus
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '8009:9090'
